import Head from 'next/head'
import { Grid, GridItem, Flex, Center, VStack, Button, Container, Input } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid templateRows="1fr 200px" minH='100vh'>
        <GridItem>
          <VStack h='100%' py={16}>
            <Container display='flex' justifyContent={'center'} gap={4} as='form'>
              <Input placeholder='Type here' />
              <Button>
                Submit
              </Button>
            </Container>
          </VStack>
        </GridItem>
        <GridItem as='footer' bgColor='gray.200' p={8}>
          <Center>
            <p>footer</p>
          </Center>
        </GridItem>
      </Grid>
    </>
  )
}
